title: My First Blog
author: Tanvi Goyal
email: your-goyaltanvi94@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This tells you about the basics of Android Development and other technologies.
  Stay Tunes!!!

# social links
github_username:  Tanvi-Goyal

show_excerpts: true # set to false to remove excerpts on the homepage

theme: jekyll-theme-minima
